on:
  push:
    tags:
      - 'v*'

name: 'Podman exporter: build and push image'

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build image
      run: make image
    - name: push image
      run: make push_image
